from datetime import datetime, timedelta

if __name__ == "__main__":
    from database import get_database
    from utils import hash_password
else:
    from .database import get_database
    from .utils import hash_password


async def seed():
    db = get_database()
    users_count = await db.users.count_documents({})
    meals_count = await db.meals.count_documents({})

    # Clear existing data
    if users_count > 0 or meals_count > 0:
        print(f"Clearing existing data ({users_count} users, {meals_count} meals)...")
        await db.users.delete_many({})
        await db.meals.delete_many({})
        print("✅ Database cleared!")

    if True:  # Always seed
        now = datetime.utcnow()

        users = [
            {
                "full_name": "Alice Johnson",
                "email": "alice@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Passionate home cook specializing in Italian and Mediterranean cuisine. Love sharing my family recipes!",
                "dietary_preferences": {
                    "dietary_restrictions": ["vegetarian-friendly"],
                    "allergens": ["shellfish"],
                    "price_range": "$$",
                    "max_distance": 25,
                    "cuisine_preferences": ["Italian", "Mediterranean", "French"],
                },
                "location": {
                    "address": "123 Main St",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62704",
                    "latitude": 39.7817213,
                    "longitude": -89.6501481,
                },
                "created_at": now,
                "updated_at": now,
            },
            {
                "full_name": "Bob Smith",
                "email": "bob@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Asian fusion enthusiast and certified sushi chef. Specializing in Japanese and Korean dishes.",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": ["peanuts"],
                    "price_range": "$$$",
                    "max_distance": 15,
                    "cuisine_preferences": ["Japanese", "Korean", "Thai"],
                },
                "location": {
                    "address": "456 Oak Ave",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62704",
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                },
                "created_at": now,
                "updated_at": now,
            },
            {
                "full_name": "Sarah Williams",
                "email": "sarah@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Baker and dessert enthusiast. Love making pastries and sweet treats!",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": ["nuts"],
                    "price_range": "$$$",
                    "max_distance": 20,
                    "cuisine_preferences": ["French", "American", "Italian"],
                },
                "location": {
                    "address": "789 Lincoln Ave",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62704",
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~3 miles from Alice (north)
            {
                "full_name": "Carlos Martinez",
                "email": "carlos@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Mexican food lover specializing in tacos and enchiladas!",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": [],
                    "price_range": "$$",
                    "max_distance": 15,
                    "cuisine_preferences": ["Mexican", "Spanish"],
                },
                "location": {
                    "address": "1500 Wabash Ave",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62704",
                    "latitude": 39.8252,
                    "longitude": -89.6501,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~5 miles from Alice (east)
            {
                "full_name": "Emily Chen",
                "email": "emily@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Chinese home cooking enthusiast. Love making dumplings and noodles!",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": ["dairy"],
                    "price_range": "$$",
                    "max_distance": 20,
                    "cuisine_preferences": ["Chinese", "Asian"],
                },
                "location": {
                    "address": "2900 S 6th St",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62703",
                    "latitude": 39.7817,
                    "longitude": -89.5556,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~10 miles from Alice (south)
            {
                "full_name": "David Thompson",
                "email": "david@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "BBQ and Southern food expert. Low and slow is the way to go!",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": [],
                    "price_range": "$$",
                    "max_distance": 25,
                    "cuisine_preferences": ["BBQ", "Southern", "American"],
                },
                "location": {
                    "address": "100 Veterans Pkwy",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62702",
                    "latitude": 39.6367,
                    "longitude": -89.6501,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~15 miles from Alice (west)
            {
                "full_name": "Sophia Patel",
                "email": "sophia@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Indian cuisine specialist with focus on vegetarian dishes and curries.",
                "dietary_preferences": {
                    "dietary_restrictions": ["vegetarian"],
                    "allergens": [],
                    "price_range": "$$",
                    "max_distance": 30,
                    "cuisine_preferences": ["Indian", "Middle Eastern"],
                },
                "location": {
                    "address": "3200 Clear Lake Ave",
                    "city": "Springfield",
                    "state": "IL",
                    "zip_code": "62702",
                    "latitude": 39.7817,
                    "longitude": -89.9336,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~20 miles from Alice (northeast)
            {
                "full_name": "Marcus Johnson",
                "email": "marcus@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Soul food chef making comfort food classics from family recipes.",
                "dietary_preferences": {
                    "dietary_restrictions": [],
                    "allergens": [],
                    "price_range": "$$",
                    "max_distance": 35,
                    "cuisine_preferences": ["Soul Food", "Southern"],
                },
                "location": {
                    "address": "500 N Main St",
                    "city": "Chatham",
                    "state": "IL",
                    "zip_code": "62629",
                    "latitude": 39.9867,
                    "longitude": -89.3831,
                },
                "created_at": now,
                "updated_at": now,
            },
            # ~25 miles from Alice (southwest)
            {
                "full_name": "Lisa Anderson",
                "email": "lisa@example.com",
                "password": hash_password("password123"),
                "verified": True,
                "role": "user",
                "status": "active",
                "bio": "Farm-to-table cooking with fresh ingredients and healthy options!",
                "dietary_preferences": {
                    "dietary_restrictions": ["vegan-friendly"],
                    "allergens": [],
                    "price_range": "$$$",
                    "max_distance": 40,
                    "cuisine_preferences": ["American", "Healthy", "Vegan"],
                },
                "location": {
                    "address": "200 W Main St",
                    "city": "Rochester",
                    "state": "IL",
                    "zip_code": "62563",
                    "latitude": 39.4192,
                    "longitude": -90.1226,
                },
                "created_at": now,
                "updated_at": now,
            },
        ]

        result = await db.users.insert_many(users)

        email_to_id = {}
        for user_doc, inserted_id in zip(users, result.inserted_ids):
            email_to_id[user_doc["email"]] = inserted_id

        expires_short = now + timedelta(days=1)

        meals = [
            # Alice Johnson - Italian/Mediterranean (5 meals)
            {
                "title": "Homemade Margherita Pizza",
                "description": "Classic Neapolitan-style pizza with fresh mozzarella, basil, and homemade tomato sauce. Made too many for dinner!",
                "sale_price": 8.00,
                "cuisine_type": "Italian",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("alice@example.com"),
                "seller_location": {
                    "latitude": 39.7817213,
                    "longitude": -89.6501481,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["gluten", "dairy"], "may_contain": []},
                "ingredients": "Pizza dough, Fresh mozzarella, Tomatoes, Basil, Olive oil, Garlic",
                "nutrition_info": "Calories: 320, Protein: 15g, Carbs: 42g, Fat: 12g",
                "photos": ["https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800"],
                "pickup_instructions": "Available today until 9 PM, meet at front lobby",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Caprese Salad with Balsamic Glaze",
                "description": "Fresh tomatoes, mozzarella, and basil drizzled with balsamic. Perfect light meal or side dish!",
                "sale_price": 6.00,
                "cuisine_type": "Italian",
                "meal_type": "Lunch",
                "seller_id": email_to_id.get("alice@example.com"),
                "seller_location": {
                    "latitude": 39.7817213,
                    "longitude": -89.6501481,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["dairy"], "may_contain": []},
                "ingredients": "Tomatoes, Fresh mozzarella, Basil, Balsamic vinegar, Olive oil",
                "nutrition_info": "Calories: 250, Protein: 12g, Carbs: 15g, Fat: 18g",
                "photos": ["https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800"],
                "pickup_instructions": "Available today, just message me",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Pesto Pasta with Sun-Dried Tomatoes",
                "description": "Homemade basil pesto tossed with penne and sun-dried tomatoes. Fresh and flavorful!",
                "sale_price": 7.50,
                "cuisine_type": "Italian",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("alice@example.com"),
                "seller_location": {
                    "latitude": 39.7817213,
                    "longitude": -89.6501481,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "3 servings",
                "allergen_info": {"contains": ["gluten", "dairy"], "may_contain": ["nuts"]},
                "ingredients": "Penne pasta, Basil pesto, Sun-dried tomatoes, Parmesan, Pine nuts",
                "nutrition_info": "Calories: 420, Protein: 14g, Carbs: 48g, Fat: 20g",
                "photos": ["https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800"],
                "pickup_instructions": "Available tonight, lobby pickup",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Mushroom Risotto",
                "description": "Creamy Arborio rice with mixed mushrooms and Parmesan. Rich and comforting!",
                "sale_price": 9.50,
                "cuisine_type": "Italian",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("alice@example.com"),
                "seller_location": {
                    "latitude": 39.7817213,
                    "longitude": -89.6501481,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["dairy"], "may_contain": []},
                "ingredients": "Arborio rice, Mixed mushrooms, Parmesan, White wine, Vegetable broth, Butter",
                "nutrition_info": "Calories: 450, Protein: 12g, Carbs: 58g, Fat: 18g",
                "photos": ["https://images.unsplash.com/photo-1609770424775-39ec362f2d94?w=800&q=60&auto=format&fit=crop&ixlib=rb-4.1.0"],
                "pickup_instructions": "Available tonight until 10 PM",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Bob Smith - Asian fusion (5 meals)
            {
                "title": "Fresh Salmon Sushi Rolls",
                "description": "California and spicy salmon rolls made with sushi-grade fish. Made fresh this afternoon!",
                "sale_price": 12.00,
                "cuisine_type": "Japanese",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("bob@example.com"),
                "seller_location": {
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "16 pieces",
                "allergen_info": {"contains": ["fish", "soy"], "may_contain": ["sesame"]},
                "ingredients": "Sushi rice, Nori, Salmon, Cucumber, Avocado, Spicy mayo, Soy sauce",
                "nutrition_info": "Calories: 320, Protein: 18g, Carbs: 42g, Fat: 10g",
                "photos": ["https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800"],
                "pickup_instructions": "Available until 8 PM",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Korean Bibimbap Bowl",
                "description": "Mixed rice bowl with seasoned vegetables, beef, and gochujang sauce. Authentic Korean comfort food!",
                "sale_price": 9.50,
                "cuisine_type": "Korean",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("bob@example.com"),
                "seller_location": {
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["soy", "sesame", "eggs"], "may_contain": []},
                "ingredients": "Rice, Beef, Spinach, Carrots, Bean sprouts, Mushrooms, Gochujang, Egg",
                "nutrition_info": "Calories: 520, Protein: 28g, Carbs: 62g, Fat: 18g",
                "photos": ["https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800"],
                "pickup_instructions": "Can meet tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Thai Pad Thai",
                "description": "Classic pad thai with shrimp, tamarind sauce, and peanuts. Sweet, sour, and savory!",
                "sale_price": 8.50,
                "cuisine_type": "Thai",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("bob@example.com"),
                "seller_location": {
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["shellfish", "eggs"], "may_contain": ["peanuts"]},
                "ingredients": "Rice noodles, Shrimp, Eggs, Tamarind, Bean sprouts",
                "nutrition_info": "Calories: 480, Protein: 24g, Carbs: 58g, Fat: 16g",
                "photos": ["https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=800"],
                "pickup_instructions": "Available this evening",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Japanese Ramen Bowl",
                "description": "Rich tonkotsu broth with ramen noodles, soft-boiled egg, and chashu pork. Made from scratch!",
                "sale_price": 11.00,
                "cuisine_type": "Japanese",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("bob@example.com"),
                "seller_location": {
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["gluten", "soy", "eggs"], "may_contain": []},
                "ingredients": "Ramen noodles, Pork broth, Chashu pork, Soft-boiled eggs, Green onions, Nori",
                "nutrition_info": "Calories: 580, Protein: 32g, Carbs: 62g, Fat: 24g",
                "photos": ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800"],
                "pickup_instructions": "Available tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Korean Kimchi Fried Rice",
                "description": "Spicy kimchi fried rice topped with a fried egg. Quick, flavorful, and satisfying!",
                "sale_price": 7.00,
                "cuisine_type": "Korean",
                "meal_type": "Lunch",
                "seller_id": email_to_id.get("bob@example.com"),
                "seller_location": {
                    "latitude": 39.7850,
                    "longitude": -89.6500,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["soy", "eggs"], "may_contain": []},
                "ingredients": "Rice, Kimchi, Eggs, Green onions, Sesame oil, Gochugaru",
                "nutrition_info": "Calories: 380, Protein: 12g, Carbs: 52g, Fat: 14g",
                "photos": ["https://images.unsplash.com/photo-1600688654899-379ec76aca42?w=800&q=60&auto=format&fit=crop&ixlib=rb-4.1.0"],
                "pickup_instructions": "Available all afternoon",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Sarah Williams - Baker/Desserts (5 meals)
            {
                "title": "Fresh Croissants",
                "description": "Buttery, flaky croissants baked fresh this morning. Made too many for the bakery test!",
                "sale_price": 6.00,
                "cuisine_type": "French",
                "meal_type": "Breakfast",
                "seller_id": email_to_id.get("sarah@example.com"),
                "seller_location": {
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "6 croissants",
                "allergen_info": {"contains": ["gluten", "dairy"], "may_contain": []},
                "ingredients": "Butter, Flour, Yeast, Milk, Sugar, Salt",
                "nutrition_info": "Calories: 230 per croissant, Fat: 12g, Carbs: 26g",
                "photos": ["https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800"],
                "pickup_instructions": "Still warm! Available now",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Chocolate Lava Cakes",
                "description": "Individual molten chocolate cakes with gooey centers. Perfect dessert!",
                "sale_price": 8.00,
                "cuisine_type": "French",
                "meal_type": "Dessert",
                "seller_id": email_to_id.get("sarah@example.com"),
                "seller_location": {
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "4 cakes",
                "allergen_info": {"contains": ["gluten", "dairy", "eggs"], "may_contain": []},
                "ingredients": "Dark chocolate, Butter, Eggs, Sugar, Flour",
                "nutrition_info": "Calories: 380, Protein: 6g, Carbs: 42g, Fat: 22g",
                "photos": ["https://images.unsplash.com/photo-1617305855058-336d24456869?w=800&q=80&auto=format&fit=crop&ixlib=rb-4.1.0"],
                "pickup_instructions": "Best served warm, come by tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Apple Pie",
                "description": "Classic American apple pie with flaky crust and cinnamon apples. Grandma's recipe!",
                "sale_price": 12.00,
                "cuisine_type": "American",
                "meal_type": "Dessert",
                "seller_id": email_to_id.get("sarah@example.com"),
                "seller_location": {
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "Whole pie (8 slices)",
                "allergen_info": {"contains": ["gluten", "dairy"], "may_contain": []},
                "ingredients": "Apples, Flour, Butter, Sugar, Cinnamon, Nutmeg",
                "nutrition_info": "Calories: 320 per slice, Carbs: 48g, Fat: 14g",
                "photos": ["https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800"],
                "pickup_instructions": "Available all day",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Cinnamon Rolls",
                "description": "Giant frosted cinnamon rolls with cream cheese icing. Soft, sweet, and perfect for breakfast!",
                "sale_price": 8.50,
                "cuisine_type": "American",
                "meal_type": "Breakfast",
                "seller_id": email_to_id.get("sarah@example.com"),
                "seller_location": {
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "6 rolls",
                "allergen_info": {"contains": ["gluten", "dairy", "eggs"], "may_contain": []},
                "ingredients": "Flour, Butter, Cream cheese, Cinnamon, Brown sugar, Yeast",
                "nutrition_info": "Calories: 420 per roll, Carbs: 58g, Fat: 18g",
                "photos": ["https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=800"],
                "pickup_instructions": "Fresh baked! Come by morning",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "French Macarons",
                "description": "Assorted French macarons in vanilla, chocolate, and raspberry flavors. Delicate and delicious!",
                "sale_price": 10.00,
                "cuisine_type": "French",
                "meal_type": "Dessert",
                "seller_id": email_to_id.get("sarah@example.com"),
                "seller_location": {
                    "latitude": 39.7881927,
                    "longitude": -89.6548106,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "12 macarons",
                "allergen_info": {"contains": ["eggs"], "may_contain": ["nuts"]},
                "ingredients": "Almond flour, Egg whites, Sugar, Buttercream, Food coloring",
                "nutrition_info": "Calories: 90 per macaron, Sugar: 10g, Fat: 4g",
                "photos": ["https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800"],
                "pickup_instructions": "Handle with care! Available today",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Carlos Martinez - Mexican (~3 miles from Alice)
            {
                "title": "Street Tacos",
                "description": "Authentic street tacos with carne asada, cilantro, and onions!",
                "sale_price": 7.00,
                "cuisine_type": "Mexican",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("carlos@example.com"),
                "seller_location": {
                    "latitude": 39.8252,
                    "longitude": -89.6501,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "5 tacos",
                "allergen_info": {"contains": [], "may_contain": []},
                "ingredients": "Corn tortillas, Beef, Cilantro, Onions, Lime",
                "nutrition_info": "Calories: 380, Protein: 24g, Carbs: 32g, Fat: 16g",
                "photos": ["https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800"],
                "pickup_instructions": "Available tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Chicken Enchiladas",
                "description": "Homemade enchiladas with red sauce and cheese. Family recipe!",
                "sale_price": 8.50,
                "cuisine_type": "Mexican",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("carlos@example.com"),
                "seller_location": {
                    "latitude": 39.8252,
                    "longitude": -89.6501,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "3 servings",
                "allergen_info": {"contains": ["dairy"], "may_contain": []},
                "ingredients": "Corn tortillas, Chicken, Red sauce, Cheese, Onions",
                "nutrition_info": "Calories: 420, Protein: 28g, Carbs: 36g, Fat: 18g",
                "photos": ["https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800"],
                "pickup_instructions": "Can meet anytime tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Emily Chen - Chinese (~5 miles from Alice)
            {
                "title": "Pork Dumplings",
                "description": "Handmade dumplings with pork filling. Made 50 of them!",
                "sale_price": 8.00,
                "cuisine_type": "Chinese",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("emily@example.com"),
                "seller_location": {
                    "latitude": 39.7817,
                    "longitude": -89.5556,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "15 dumplings",
                "allergen_info": {"contains": ["gluten", "soy"], "may_contain": []},
                "ingredients": "Dumpling wrappers, Ground pork, Cabbage, Ginger, Soy sauce",
                "nutrition_info": "Calories: 360, Protein: 20g, Carbs: 42g, Fat: 12g",
                "photos": ["https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800"],
                "pickup_instructions": "Available all evening",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Lo Mein Noodles",
                "description": "Stir-fried lo mein with vegetables and chicken. Quick and tasty!",
                "sale_price": 7.50,
                "cuisine_type": "Chinese",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("emily@example.com"),
                "seller_location": {
                    "latitude": 39.7817,
                    "longitude": -89.5556,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": ["gluten", "soy"], "may_contain": []},
                "ingredients": "Lo mein noodles, Chicken, Mixed vegetables, Soy sauce, Garlic",
                "nutrition_info": "Calories: 420, Protein: 24g, Carbs: 52g, Fat: 14g",
                "photos": ["https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800"],
                "pickup_instructions": "Available tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # David Thompson - BBQ (~10 miles from Alice)
            {
                "title": "Smoked Pulled Pork",
                "description": "Slow-smoked pulled pork with BBQ sauce. Fall-apart tender!",
                "sale_price": 10.00,
                "cuisine_type": "BBQ",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("david@example.com"),
                "seller_location": {
                    "latitude": 39.6367,
                    "longitude": -89.6501,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "3 servings",
                "allergen_info": {"contains": [], "may_contain": []},
                "ingredients": "Pork shoulder, BBQ rub, BBQ sauce, Smoke",
                "nutrition_info": "Calories: 380, Protein: 32g, Carbs: 18g, Fat: 20g",
                "photos": ["https://plus.unsplash.com/premium_photo-1740256292155-35a3db89f537?w=800"],
                "pickup_instructions": "Available all day",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Sophia Patel - Indian (~15 miles from Alice)
            {
                "title": "Vegetable Curry",
                "description": "Aromatic vegetable curry with basmati rice. Vegan and delicious!",
                "sale_price": 8.00,
                "cuisine_type": "Indian",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("sophia@example.com"),
                "seller_location": {
                    "latitude": 39.7817,
                    "longitude": -89.9336,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": [], "may_contain": []},
                "ingredients": "Mixed vegetables, Curry spices, Coconut milk, Basmati rice",
                "nutrition_info": "Calories: 380, Protein: 12g, Carbs: 58g, Fat: 12g",
                "photos": ["https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800"],
                "pickup_instructions": "Available this evening",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Samosas",
                "description": "Crispy vegetable samosas with tamarind chutney. Perfect snack!",
                "sale_price": 6.00,
                "cuisine_type": "Indian",
                "meal_type": "Snack",
                "seller_id": email_to_id.get("sophia@example.com"),
                "seller_location": {
                    "latitude": 39.7817,
                    "longitude": -89.9336,
                    "city": "Springfield",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "6 samosas",
                "allergen_info": {"contains": ["gluten"], "may_contain": []},
                "ingredients": "Potatoes, Peas, Pastry dough, Spices, Tamarind chutney",
                "nutrition_info": "Calories: 280, Protein: 6g, Carbs: 38g, Fat: 12g",
                "photos": ["https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800"],
                "pickup_instructions": "Hot and fresh! Available now",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Marcus Johnson - Soul Food (~20 miles from Alice)
            {
                "title": "Fried Chicken",
                "description": "Southern fried chicken with secret seasoning. Crispy and juicy!",
                "sale_price": 9.50,
                "cuisine_type": "Soul Food",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("marcus@example.com"),
                "seller_location": {
                    "latitude": 39.9867,
                    "longitude": -89.3831,
                    "city": "Chatham",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "4 pieces",
                "allergen_info": {"contains": ["gluten", "dairy"], "may_contain": []},
                "ingredients": "Chicken, Buttermilk, Flour, Spices",
                "nutrition_info": "Calories: 480, Protein: 35g, Carbs: 22g, Fat: 28g",
                "photos": ["https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800"],
                "pickup_instructions": "Available tonight",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Mac and Cheese",
                "description": "Baked mac and cheese with extra cheese. Ultimate comfort food!",
                "sale_price": 6.50,
                "cuisine_type": "Soul Food",
                "meal_type": "Dinner",
                "seller_id": email_to_id.get("marcus@example.com"),
                "seller_location": {
                    "latitude": 39.9867,
                    "longitude": -89.3831,
                    "city": "Chatham",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "4 servings",
                "allergen_info": {"contains": ["gluten", "dairy", "eggs"], "may_contain": []},
                "ingredients": "Macaroni, Cheddar cheese, Milk, Butter, Eggs",
                "nutrition_info": "Calories: 480, Protein: 18g, Carbs: 48g, Fat: 24g",
                "photos": ["https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800"],
                "pickup_instructions": "Hot from the oven!",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },

            # Lisa Anderson - Farm-to-table (~25 miles from Alice)
            {
                "title": "Quinoa Buddha Bowl",
                "description": "Healthy buddha bowl with quinoa, roasted veggies, and tahini. Vegan!",
                "sale_price": 9.00,
                "cuisine_type": "Healthy",
                "meal_type": "Lunch",
                "seller_id": email_to_id.get("lisa@example.com"),
                "seller_location": {
                    "latitude": 39.4192,
                    "longitude": -90.1226,
                    "city": "Rochester",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "2 servings",
                "allergen_info": {"contains": [], "may_contain": ["sesame"]},
                "ingredients": "Quinoa, Sweet potato, Chickpeas, Kale, Tahini, Lemon",
                "nutrition_info": "Calories: 420, Protein: 16g, Carbs: 58g, Fat: 14g",
                "photos": ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800"],
                "pickup_instructions": "Fresh and ready!",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
            {
                "title": "Veggie Wraps",
                "description": "Fresh vegetable wraps with hummus and sprouts. Light and healthy!",
                "sale_price": 7.00,
                "cuisine_type": "Vegan",
                "meal_type": "Lunch",
                "seller_id": email_to_id.get("lisa@example.com"),
                "seller_location": {
                    "latitude": 39.4192,
                    "longitude": -90.1226,
                    "city": "Rochester",
                    "state": "IL",
                },
                "status": "available",
                "available_for_sale": True,
                "available_for_swap": True,
                "portion_size": "3 wraps",
                "allergen_info": {"contains": ["gluten"], "may_contain": []},
                "ingredients": "Whole wheat tortillas, Hummus, Lettuce, Tomato, Cucumber, Sprouts",
                "nutrition_info": "Calories: 320, Protein: 12g, Carbs: 48g, Fat: 10g",
                "photos": ["https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800"],
                "pickup_instructions": "Available all day",
                "preparation_date": now,
                "expires_date": expires_short,
                "created_at": now,
                "updated_at": now,
            },
        ]

        meals_result = await db.meals.insert_many(meals)

        print(
            f"✅ Seeded {len(result.inserted_ids)} users and {len(meals_result.inserted_ids)} meals"
        )


if __name__ == "__main__":
    import asyncio
    from database import connect_to_mongo, close_mongo_connection

    async def main():
        await connect_to_mongo()
        await seed()
        await close_mongo_connection()

    asyncio.run(main())
